### ISSUE TITLE
Multiple changes/adds

### ISSUE THREAD

**Issue by tcarrondo** [datarootsio/terraform-module-kubernetes-application#16]
I'm planning on using your module but to do that I need to add the following features:
- additional annotations;
- Affinity and anti-affinity;
- strategy;
- init container;
- hosts;
- replicas;
Also I need to make linkerd annotations optional.
Does this make sense to you for the future development of this module?

(I'm  available to do this changes, are you interested on the PR?)

**Comment by sam-dumont** [comment]
Hi Tiago,

I'm glad to see that our module can be useful to you! I'm currently on holidays and will be back in 10 days, so if you want to propose a PR, go for it! My colleague @Gfeuillen can look into that. The most important is to be able to support the variety of configurations that will make this module useful, you can look at how we use the lookup feature to give freedom to the user. Thanks for the interest! 😁

**Comment by tcarrondo** [comment]
Perfect! I will do that.

**Comment by tcarrondo** [comment]
I have created separate issue for easy tracking each task.
Closing this issue.
